# Generated by Django 4.2.2 on 2025-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Marks', models.IntegerField()),
                ('Location', models.CharField(max_length=20)),
                ('Join_Date', models.DateField()),
            ],
        ),
    ]
