# Generated by Django 4.2.2 on 2025-03-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pname', models.CharField(max_length=30)),
                ('Pprice', models.IntegerField()),
                ('Pcolor', models.CharField(max_length=40)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
