# Generated by Django 4.2.2 on 2025-07-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoterId', models.IntegerField()),
                ('VoterName', models.CharField(max_length=20)),
                ('VoterAge', models.IntegerField()),
                ('VoterAddress', models.CharField(max_length=30)),
            ],
        ),
    ]
