# Generated by Django 4.2.2 on 2025-07-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=35)),
                ('Lname', models.CharField(max_length=43)),
                ('RollNo', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Grade', models.FloatField()),
            ],
        ),
    ]
