# Generated by Django 4.2.2 on 2025-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleParking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VehicleNum', models.CharField(max_length=20)),
                ('VehicleName', models.CharField(max_length=20)),
                ('VehicleWheels', models.IntegerField()),
                ('VehicleToken', models.IntegerField()),
            ],
        ),
    ]
