# Generated by Django 4.2.2 on 2025-06-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0003_alter_vehicleparking_parking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleparking',
            name='Parking_Date',
        ),
    ]
