# Generated by Django 4.2.2 on 2025-06-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EFname', models.CharField(max_length=20)),
                ('ELname', models.CharField(max_length=20)),
                ('ESalary', models.IntegerField()),
            ],
        ),
    ]
